---
- name: restart mysqld exporter
  become: true
  systemd:
    daemon_reload: true
    name: mysqld_exporter
    state: restarted

- name: Ensure mysqld_exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: mysqld_exporter
    enabled: true
