---
- name: Prepare
  hosts: all
  tasks:
  - name: Gather variables for each operating system
    debug:
      var: ansible_distribution
  - name: Install mysqld server
    package:
      name: "mariadb-server"
      state: present
  - name: Start mysql server
    systemd:
      name: "{{ item }}"
      state: started
    failed_when: false
    with_items:
      - mysql
      - mysqld
      - mariadb
